# -*- encoding: utf-8 -*-

# taken from https://en.wikipedia.org/wiki/Help:Citation_Style_1
citation_template_names = set([
    'Citation',
    'Cite arXiv',
    'Cite AV media',
    'Cite AV media notes',
    'Cite book',
    'Cite conference',
    'Cite encyclopedia',
    'Cite episode',
    'Cite interview',
    'Cite journal',
    'Cite magazine',
    'Cite mailing list',
    'Cite map',
    'Cite news',
    'Cite newsgroup',
    'Cite podcast',
    'Cite press release',
    'Cite report',
    'Cite serial',
    'Cite sign',
    'Cite speech',
    'Cite tech report',
    'Cite thesis',
    'Cite web',
    'Cita',
    'Cita libro',
    'Cita pubblicazione',
    'Cita web',
    'Cita legge italiana',
    'Cita brevetto',
    'Cita conferenza',
    'Cita news',
    'Cita video',
    'Cita TV'
    ])
