dist: focal
language: python
python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - 3.10
arch:
  - amd64
  - ppc64le
install:
    - pip install coveralls pytest
    - python setup.py develop
script:
    - coverage run --source=mwparserfromhell -m pytest
after_success:
    - coveralls
env:
  matrix:
    - WITHOUT_EXTENSION=0
    - WITHOUT_EXTENSION=1
